import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  return (
    <>
      <Head>
        <title>Dynamic Routes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
      <h1 className="text-3xl font-bold underline">
      Hello world!
    </h1>
    <button className='bg-blue-400 text-xl pt-3 pb-3 pl-2 pr-2 rounded-md'><Link href="/products">Products</Link></button>
      {/* <Home /> */}
      </main>
    </>
  )
}